repository_type: pipeline

nf_core_version: 4.0.2

lint:
  files_unchanged:
    - CODE_OF_CONDUCT.md
    - assets/nf-core-nextflow_for_ichorcna_logo_light.png
    - docs/images/nf-core-nextflow_for_ichorcna_logo_light.png
    - docs/images/nf-core-nextflow_for_ichorcna_logo_dark.png
    - .github/ISSUE_TEMPLATE/bug_report.yml
    - .github/PULL_REQUEST_TEMPLATE.md
    - assets/email_template.txt
    - docs/README.md
  nextflow_config:
    - manifest.name
    - manifest.homePage
  multiqc_config:
    - report_comment
  files_exist:
    - CODE_OF_CONDUCT.md
    - assets/nf-core-nextflow_for_ichorcna_logo_light.png
    - docs/images/nf-core-nextflow_for_ichorcna_logo_light.png
    - docs/images/nf-core-nextflow_for_ichorcna_logo_dark.png
    - .github/ISSUE_TEMPLATE/config.yml
    - .github/workflows/awstest.yml
    - .github/workflows/awsfulltest.yml

template:
  org: nf-core
  name: nextflow_for_ichorcna
  description: Automatic usage of ichorcna on wes bam
  author: Tommaso Regoli
  version: 1.0.0dev
  force: true
  outdir: .
  skip_features:
    - gpu
  is_nfcore: false
