contact_links:
  - name: Join nf-core
    url: https://nf-co.re/join
    about: Please join the nf-core community here
  - name: "Slack #nextflow_for_ichorcna channel"
    url: https://nfcore.slack.com/channels/nextflow_for_ichorcna
    about: Discussion about the nf-core/nextflow_for_ichorcna pipeline
